In [1]:
import numpy as np

In [4]:
n1= np.array(3,3)

TypeError: Cannot interpret '3' as a data type

In [5]:
l1 = [1,2,3,4]

In [6]:
n1 = np.array(l1)

In [7]:
n1

array([1, 2, 3, 4])

In [8]:
n1 = np.full((2,2),10)

In [9]:
n1


array([[10, 10],
       [10, 10]])

In [12]:
n2 = np.arange(50,100)

In [13]:
n2

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
n2= np.arange(50,100,10)

In [15]:
n2

array([50, 60, 70, 80, 90])

In [16]:
n3 = np.random.randint(1,100,5)

In [17]:
n3

array([30, 34, 33, 60, 60])

In [18]:
n1 = np.array([[1,2,3,4],[4,3,2,1]])

In [19]:
n1.shape

(2, 4)

In [20]:
n1.shape = (4,2)

In [21]:
n1

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [22]:
n2

array([50, 60, 70, 80, 90])

In [23]:
n1 = np.array([10,20,30])

In [24]:
n2 = np.array([40,50,60])

In [27]:
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [28]:
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [29]:
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [30]:
n1 = np.array([30,40,50,60])

In [31]:
n2 = np.array([50,60,70,80])

In [33]:
np.intersect1d(n1,n2)

array([50, 60])

In [37]:
np.sum((n1,n2))


440

In [38]:
np.sum([n1,n2],axis = 1)

array([180, 260])

In [39]:
n1 = n1+1

In [40]:
n1

array([31, 41, 51, 61])

In [41]:
np.mean(n1)

46.0

In [42]:
np.std(n1)

11.180339887498949

In [43]:
np.median(n1)

46.0

In [45]:
n1 = np.random.randint(1,100,10)

In [46]:
np.mean(n1)

48.9

In [47]:
n1

array([62, 84,  1, 93, 77,  2, 15, 51, 73, 31])

In [48]:
np.mean(n1)

48.9

In [49]:
n1

array([62, 84,  1, 93, 77,  2, 15, 51, 73, 31])

In [50]:
n1


array([62, 84,  1, 93, 77,  2, 15, 51, 73, 31])

In [51]:
np.save('my_array',n1)

In [53]:
new_n1 = np.load('my_array.npy')

In [54]:
new_n1

array([62, 84,  1, 93, 77,  2, 15, 51, 73, 31])